/*
  # Week 1 Day 1: Add synthesizer_metadata, quality_score and related fields to sessions table

  ## Overview
  This migration adds essential columns for storing synthesizer output and data quality metrics
  that are generated by the agents pipeline but were previously being lost (no persistence).

  ## New Columns

  ### synthesizer_metadata (jsonb)
  - top_3_insights: array of key insights from the session
  - root_cause: primary technical issue identified
  - delta_headline: comparison headline vs previous session
  - fatigue_analysis: fatigue assessment across strokes
  - comparison_delta: detailed comparison metrics vs previous session

  ### quality_score (jsonb)
  - mediapipe_coverage: % of frames with valid pose data
  - ball_sync_rate: % of frames with synchronized ball detection
  - overall_quality_score: 0-1 aggregate quality metric
  - processing_gaps_percent: % of frames with processing issues

  ### Other missing fields
  - actual_session_date: session date from metadata (may differ from created_at)
  - camera_orientation: how the camera was positioned
  - equipment_used: racket, shoes, etc. as JSON
  - prioridades_mejora: priority improvement areas (already in code, missing from schema)
  - raw_data: complete raw output from vision/agents pipelines as JSON blob

  ## Default Values
  All new fields default to empty objects/null to maintain backward compatibility.

  ## Validation
  Run this BEFORE deploying the week 1 code:
    SELECT COUNT(*) FROM sessions WHERE digital_twin_data IS NOT NULL;
    -- Should return 0 before we drop the column
*/

-- Add synthesizer_metadata and quality_score columns
ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS synthesizer_metadata jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS quality_score jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS actual_session_date timestamptz,
  ADD COLUMN IF NOT EXISTS camera_orientation text,
  ADD COLUMN IF NOT EXISTS equipment_used jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS prioridades_mejora jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS raw_data jsonb DEFAULT '{}'::jsonb;

-- Create indexes for frequently queried fields
CREATE INDEX IF NOT EXISTS sessions_synthesizer_metadata_idx
  ON sessions USING GIN (synthesizer_metadata);
CREATE INDEX IF NOT EXISTS sessions_quality_score_idx
  ON sessions USING GIN (quality_score);
CREATE INDEX IF NOT EXISTS sessions_actual_session_date_idx
  ON sessions (actual_session_date DESC NULLS LAST);

-- Optional: Drop digital_twin_data column if it exists and contains only NULLs
-- (commented out for safety — validate manually before uncommenting)
-- ALTER TABLE sessions DROP COLUMN IF EXISTS digital_twin_data;
